apiVersion: v1
kind: Service
metadata:
  name: core-service
  namespace: cargotrack
  labels:
    app.kubernetes.io/name: core-service
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app: core-service
  ports:
    - name: http
      protocol: TCP
      port: 4000
      targetPort: http
